name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build LogicAndTestsOnly.slnf --no-restore
    - name: Test
      run: dotnet test LogicAndTestsOnly.slnf --no-build --verbosity normal /logger:"trx;LogFileName=GenOne.trx"
      
      

    - name: Install Testspace Module
      uses: testspace-com/setup-testspace@v1
      with:
        domain: ${{ github.repository_owner }}

    - name: Create test reports
      run: |
        testspace './*.trx'
      if: always()
